plugins {
    id 'com.android.application'
}

def appVersionCode = 6
def appVersionName = '1.0.5'
def secureSigningScript = providers.gradleProperty('secure.signing').orNull
def secureSigningFile = secureSigningScript == null ? null : rootProject.file(secureSigningScript)

base {
    archivesName.set("${appVersionName}[${appVersionCode}]AtlasAppWidget")
}

android {
    namespace 'mmwtl.atlaswidget'
    compileSdk 36

    defaultConfig {
        applicationId 'mmwtl.atlaswidget'
        minSdk 30
        targetSdk 36
        versionCode appVersionCode
        versionName appVersionName
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

if (secureSigningFile != null && secureSigningFile.isFile()) {
    apply from: secureSigningFile
}
